version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:


  build-push-frontend:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push frontend image
          command: |
            echo "Building frontend image..."
            cd frontend
            docker build -t sheenandeh333/eks-app-frontend:latest .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push sheenandeh333/eks-app-frontend:latest

  build-push-backend:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push backend image
          command: |
            echo "Building backend image..."
            cd backend
            docker build -t sheenandeh333/eks-app-backend:latest .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push sheenandeh333/eks-app-backend:latest



  deploy-to-eks:
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Update kubeconfig
          command: aws eks update-kubeconfig --name eks-nebulance --region eu-central-1
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - run:
          name: Deploy using Helm
          command: |
            helm upgrade --install nebulance ./helm-charts \
              --namespace nebulance \
              --wait \
              --timeout 10m

workflows:
  version: 2
  build-tag-deploy:
    jobs:
      - build-push-frontend:
          filters:
            branches:
              only: main
      - build-push-backend:
          filters:
            branches:
              only: main
      - deploy-to-eks:
          requires:
            - build-push-frontend
            - build-push-backend
          filters:
            branches:
              only: main