version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  build-push-update:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build, Push, and Update image tags
          command: |
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            FRONTEND_TAG="1.0.0-${TIMESTAMP}"
            BACKEND_TAG="1.0.0-${TIMESTAMP}"

            echo "🛠 Building and pushing frontend..."
            cd frontend
            docker build -t sheenandeh333/eks-app-frontend:${FRONTEND_TAG} .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push sheenandeh333/eks-app-frontend:${FRONTEND_TAG}
            cd ..

            echo "🛠 Building and pushing backend..."
            cd backend
            docker build -t sheenandeh333/eks-app-backend:${BACKEND_TAG} .
            docker push sheenandeh333/eks-app-backend:${BACKEND_TAG}
            cd ..

            echo "📝 Updating Helm values.yaml..."
            sed -i "s|tag: \".*\"|tag: \"${FRONTEND_TAG}\"|" helm-charts/values.yaml
            sed -i "s|repository: sheenandeh333/eks-app-backend.*|repository: sheenandeh333/eks-app-backend\n    tag: \"${BACKEND_TAG}\"|" helm-charts/values.yaml

            echo "🔐 Git commit updated values.yaml..."
            git config --global user.email "ci@example.com"
            git config --global user.name "CircleCI"
            git add helm-charts/values.yaml
            git commit -m "Update FE & BE tags to FE:${FRONTEND_TAG}, BE:${BACKEND_TAG}"
            git push origin main

  deploy-to-eks:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Update kubeconfig
          command: aws eks update-kubeconfig --name eks-nebulance --region eu-central-1
      - run:
          name: Deploy using Helm
          command: |
            helm upgrade --install nebulance ./helm-charts \
              --namespace nebulance \
              --wait \
              --timeout 10m

workflows:
  version: 2
  build-tag-deploy:
    jobs:
      - build-push-update:
          filters:
            branches:
              only: main
      - deploy-to-eks:
          requires:
            - build-push-update
          filters:
            branches:
              only: main