apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebulance
  namespace: argocd
spec:
  project: enterprise-app
  source:
    repoURL: https://github.com/sheenandeh/Enterprise-App.git  # Update this to your actual repository URL
    targetRevision: main
    path: helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: nebulance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true