apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  annotations:
    {{- toYaml .Values.frontend.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.frontend.name }}